### ISSUE TITLE
Example best practies repo

### ISSUE THREAD

**Issue by BondarenkoAlex** [lirantal/nodejs-cli-apps-best-practices#121]
Hello.
Do you have/know a simple repo with cli best practies?
I need simple example cli app.

**Comment by lirantal** [comment]
Check the README of this repository... :)

**Comment by BondarenkoAlex** [comment]
)))))
Thank you.
Best practices from readme file is a best information, but...
I would want to get a simple code cli`s application as base code. Or spy on a cool code.
May be you know simple/easy a cli app repo?

**Comment by lirantal** [comment]
I didn't mean it in a snarky way. I genuinely meant look at the README. There are referenced examples of Node.js CLI that others or myself have built.
