### ISSUE TITLE
Updating layout suggestions

### ISSUE THREAD

**Issue by lirantal** [lirantal/nodejs-cli-apps-best-practices#17]
What are your thoughts around organizing the layouts a bit differently?

Some feedback I received is around:
- [x] Getting rid of the collapsible content such as in Details or Recommended packages part and then just defaulting to that content being visible straight-out.
- [x] Adding a TL;DR for the top of the guide instead of the short intro, is that more helpful or not much of a change of what we have today?
- [x] Should we add more space between items and also between end/beginning of sections?
- [x] I want to add a contributors section too based on https://allcontributors.org/

**Comment by lzm0x219** [comment]
The existing bug of gitlocalize can be circumvented by directly displaying the details. I think it is helpful to add TL;DR.

**Comment by lirantal** [comment]
Sounds good, I'll plan for both of these updates then 👌

**Comment by lzm0x219** [comment]
Great!👏

**Comment by lzm0x219** [comment]
Will you consider building a documentation website?

**Comment by lirantal** [comment]
I'm open to do that if someone wants to suggest pushing a docs directory for it and then we can also easily host it on GitHub Pages.

**Comment by lzm0x219** [comment]
Yeah, it's great!  I've been working on a vuepress theme recently. what tools are you going to use?

**Comment by lirantal** [comment]
Didn't have anything in mind so whichever works and Vuepress is fine with me. Will it handle the current markdown style we have on the README though?

**Comment by lzm0x219** [comment]
It can be handled. Vuepress makes people focus on writing documents.

**Comment by lirantal** [comment]
Can you provide an example of a markdown type of README page and how does the vuepress visuals of it look like?

**Comment by lzm0x219** [comment]
This is the effect of the default theme：

example：https://vuepress.vuejs.org/
source：https://github.com/vuejs/vuepress/blob/master/packages/docs/docs/README.md

**Comment by lirantal** [comment]
If you can put up a quick example of how the README would look like that would be great. I was hoping for some kind of layout where the table of contents would be on the left, and the right would have the actual content and so navigation will be really easy.

**Comment by lzm0x219** [comment]
I am still developing such a theme, maybe https://v2.docusaurus.io/ is more suitable

**Comment by lirantal** [comment]
That's ok. Not super important and we'll get to it later on is just fine.

**Comment by lzm0x219** [comment]
👌

**Comment by lirantal** [comment]
@all-contributors please add @vvni for translation

**Comment by lirantal** [comment]
@all-contributors please add @terkelg @jasonkarns for content
@all-contributors please add @davesag for maintenance

**Comment by lirantal** [comment]
@all-contributors please add @terkelg @jasonkarns for content

**Comment by lirantal** [comment]
@all-contributors please add @jasonkarns for content

**Comment by lirantal** [comment]
@all-contributors please add @davesag for maintenance

**Comment by lzm0x219** [comment]
🎉

**Comment by lirantal** [comment]
I'll figure out the spacing later.
I think can close the issue for now
