### ISSUE TITLE
GitLocalize: Problems with the structure of the .md file

### ISSUE THREAD

**Issue by JoseJPR** [lirantal/nodejs-cli-apps-best-practices#56]
Hi everyone,

GitLocalize is giving me some trouble after a few weeks of inactivity in Spanish translations. It seems it isn´t maintaining the structure of the .md file.

Has anyone had this problem? How have they solved it?

<img width="1132" alt="Captura de pantalla 2020-06-16 a las 7 48 09" src="https://user-images.githubusercontent.com/12954959/84736268-c05ce700-afa5-11ea-8924-99bc94ff84d7.png">

My idea to solve it would be in this case not to work via GitLocalize and create a PR.

**Comment by lirantal** [comment]
@vvni maybe you had this issue and can help Jose?

**Comment by JoseJPR** [comment]
Hi team, @lirantal  and @vvni, can you help me with this issue?

I think I can solve it by doing the manual translation with my code editor and send you a PR.

Any other idea?

**Comment by lirantal** [comment]
@JoseJPR what exactly is the issue?
Is there anything I can do with the git localize platform to help here?

**Comment by JoseJPR** [comment]
In summary it seems that the platform repeats content, you can see it in the usernames.
Don´t worry, I will use a PR without git localize in order to advance and resolve this conflicts. Then I can get back to the git localize platform.

**Comment by lirantal** [comment]
Thanks!
