### ISSUE TITLE
New feature: document other CLI related resources

### ISSUE THREAD

**Issue by lirantal** [lirantal/nodejs-cli-apps-best-practices#77]
Document other resources like:
1. https://clig.dev/
2. https://primer.style/cli/getting-started/principles

as additional educational material 

--- 

## Expected scope of work for this issue:

- The README currently has 8 sections
- Let's add a new section called: `10 Appendix: CLI educational resources`
- In it, let's document the above suggested resources
- Let's not do the other section's format of "DO and OTHERWISE" because it doesn't fit. Instead, should we use a table to document them with some other properties, or perhaps just a bulleted list? Happy to go with whatever makes the most sense and we can change later.

**Comment by S0han** [comment]
can you further explain exactly what needs to be done for this issue?

**Comment by lirantal** [comment]
I updated the description for the work on this issue.
Thanks for chiming in here too @S0han.

**Comment by MichalPorag** [comment]
@lirantal Can I take it?

**Comment by lirantal** [comment]
Please do 👍🏽

**Comment by lirantal** [comment]
Fixed in #91
