### ISSUE TITLE
New feature: document a new section for popular command line frameworks 

### ISSUE THREAD

**Issue by lirantal** [lirantal/nodejs-cli-apps-best-practices#78]
Feature a new section to include popular tools to build CLIs, such as:
1. oclif
2. inquirer
3. ink
4. blessed

---

## Expected scope of work for this issue:

- The README currently has 8 sections
- Let's add a new section called: `9 Appendix: CLI Frameworks`
- In it, let's document the above suggested frameworks
- Let's not do the other section's format of "DO and OTHERWISE" because it doesn't fit. Instead, I suggest we create a table with the library name, another column for the npm package, and another column for the github repo. We can add another column that has badges of current stars and npm downloads. Anything else you can think of that would be helpful?

**Comment by S0han** [comment]
what do you need me to do to help fix this issue?

**Comment by lirantal** [comment]
Hi @S0han 👋

Thanks for chiming in - I updated the description above.
Happy if you want to take it :)

**Comment by S0han** [comment]
im kinda new to open source im down to help if you can further explain

**Comment by lirantal** [comment]
Sure! If you're new to using GitHub and contributing via a pull request to a project, I recommend these guides to catch up on it:
1. https://opensource.guide/how-to-contribute/
2. https://github.com/firstcontributions/first-contributions

And once you feel comfortable doing that, you can make the updates as described in the issue above to the `README.md` file that has all the contents.

**Comment by S0han** [comment]
thanks!

**Comment by S0han** [comment]
im ready to give it a try

**Comment by lirantal** [comment]
Fixed by @UrielOfir 👏 👏 👏
