### ISSUE TITLE
Cleanup configuration files (if any) when uninstalling the package

### ISSUE THREAD

**Issue by m-sureshraj** [lirantal/nodejs-cli-apps-best-practices#8]
This could be a new topic. The CLI application should remove it's internal configuration files (if there are any) when uninstalling the package. We can use NPM's `pre` or `post` uninstall script for this purpose.

https://docs.npmjs.com/misc/scripts

**Comment by lirantal** [comment]
Sounds like a good idea to add in the `Distribution` section 👍

**Comment by lirantal** [comment]
@m-sureshraj perhaps wasn't clear from my previous comment - you are more than welcome to PR this idea and we can work out the exact semantics and suggestions via the PR.

**Comment by m-sureshraj** [comment]
Sure @lirantal. I will create a PR for this topic. Thanks.

**Comment by jasonkarns** [comment]
Even better if the user can opt-in to preserving config files. Many times it's valuable for the config to persist across installations.

**Comment by m-sureshraj** [comment]
Hi, I've created PR for this topic. Please review - https://github.com/lirantal/nodejs-cli-apps-best-practices/pull/16

cc: @lirantal @jasonkarns
