### ISSUE TITLE
Can I use GitLocalize to translate documents？

### ISSUE THREAD

**Issue by lzm0x219** [lirantal/nodejs-cli-apps-best-practices#9]
I want to translate the Chinese version.

**Comment by lirantal** [comment]
Looks wonderful. I'll go ahead and add this integration

**Comment by lirantal** [comment]
Thank you for chiming in ❤️

Great idea! I added you to the project on GitLocalize so you can moderate translations on for Chinese.

**Comment by lzm0x219** [comment]
> Thank you for chiming in ❤️
> 
> Great idea! I added you to the project on GitLocalize so you can moderate translations on for Chinese.

Great! 🤝

**Comment by lzm0x219** [comment]
GitLocalize is abnormal, wait for the official to fix the problem, and then continue to translate the document.

**Comment by lzm0x219** [comment]
@lirantal The basic translation is complete, and there is one place that needs to be translated manually and cannot be done in gitlocalize.

**Comment by lirantal** [comment]
That's amazing @vvni 🎉 
What is the process we need to follow now with GitLocalize?

Looks like we're 77% there but we can only create a pull request to land the changes when it reaches 100%. What do you suggest we do?

![image](https://user-images.githubusercontent.com/316371/74917148-bba96d00-53cf-11ea-9fc3-d10add965874.png)

**Comment by lzm0x219** [comment]
@lirantal  I will fix it.😄

**Comment by lirantal** [comment]
Thanks!

**Comment by lirantal** [comment]
Merged in #18
